require_relative 'rangama/base_dictionary'
require_relative 'rangama/dictionary'
require_relative 'rangama/permutation_array'
require_relative 'rangama/sorted_dictionary'
require_relative 'rangama/base_search'
require_relative 'rangama/search'
require_relative 'rangama/fast_search'
require_relative 'rangama/result_presenter'
